server:
  port: 8080

spring:
  application:
    name: notes-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notesdb

management:
  endpoints:
    web:
      exposure:
        include: health,info
